# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DUŠAN ORLOVIĆ PR TRK INFORMACIJE
email: salji@trk.in.rs
phone: +381 63 8997157
description: > # this means to ignore newlines until "baseurl:"
  DUŠAN ORLOVIĆ PR PROGRAMIRANJE TRK INFORMACIJE NOVI SAD
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.trk.in.rs" # the base hostname & protocol for your site
github_username:  duleorlovic

# Build settings
markdown: kramdown
